/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Galerians)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80165314u
#define func_80165314 BootEntry  /* alias */
